<?xml version="1.0"?>
<!-- Autor: Camilo Soto Villegas | Contacto: camilo.soto.v@usach.cl | Proyecto: clean_v2 -->
<robot name="mm_mobile_manipulator" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find mm_base_description)/urdf/mm_base_macro.xacro"/>
  <xacro:include filename="$(find mm_arm_description)/urdf/mm_arm_macro.xacro"/>

  <xacro:arg name="prefix" default="mm1_"/>
  <xacro:arg name="namespace" default="mm1"/>
  <xacro:arg name="scale" default="1.0"/>
  <xacro:arg name="controllers_file" default=""/>
  <xacro:arg name="enable_ros2_control" default="true"/>
  <xacro:arg name="visual_mode" default="full"/>

  <xacro:arg name="arm_x" default="0.0"/>
  <xacro:arg name="arm_y" default="0.0"/>
  <xacro:arg name="arm_z" default="0.015"/>
  <xacro:arg name="arm_roll" default="0.0"/>
  <xacro:arg name="arm_pitch" default="0.0"/>
  <xacro:arg name="arm_yaw" default="0.0"/>
  <xacro:arg name="enable_lidar" default="true"/>
  <xacro:arg name="lidar_x" default="0.20"/>
  <xacro:arg name="lidar_y" default="0.0"/>
  <xacro:arg name="lidar_z" default="0.125"/>
  <xacro:arg name="cam_front_x" default="0.27"/>
  <xacro:arg name="cam_front_y" default="0.0"/>
  <xacro:arg name="cam_front_z" default="0.085"/>
  <xacro:arg name="cam_front_roll" default="0.0"/>
  <xacro:arg name="cam_front_pitch" default="0.0"/>
  <xacro:arg name="cam_front_yaw" default="0.0"/>
  <xacro:arg name="cam_left_x" default="0.0"/>
  <xacro:arg name="cam_left_y" default="0.19"/>
  <xacro:arg name="cam_left_z" default="0.085"/>
  <xacro:arg name="cam_left_roll" default="0.0"/>
  <xacro:arg name="cam_left_pitch" default="0.0"/>
  <xacro:arg name="cam_left_yaw" default="1.5708"/>
  <xacro:arg name="cam_right_x" default="0.0"/>
  <xacro:arg name="cam_right_y" default="-0.19"/>
  <xacro:arg name="cam_right_z" default="0.085"/>
  <xacro:arg name="cam_right_roll" default="0.0"/>
  <xacro:arg name="cam_right_pitch" default="0.0"/>
  <xacro:arg name="cam_right_yaw" default="-1.5708"/>
  <xacro:arg name="cam_rear_x" default="-0.27"/>
  <xacro:arg name="cam_rear_y" default="0.0"/>
  <xacro:arg name="cam_rear_z" default="0.085"/>
  <xacro:arg name="cam_rear_roll" default="0.0"/>
  <xacro:arg name="cam_rear_pitch" default="0.0"/>
  <xacro:arg name="cam_rear_yaw" default="3.1416"/>
  <xacro:arg name="ee_cam_mount_x" default="0.055"/>
  <xacro:arg name="ee_cam_mount_y" default="0.0"/>
  <xacro:arg name="ee_cam_mount_z" default="0.02"/>
  <xacro:arg name="ee_cam_mount_roll" default="0.0"/>
  <xacro:arg name="ee_cam_mount_pitch" default="0.0"/>
  <xacro:arg name="ee_cam_mount_yaw" default="0.0"/>
  <xacro:arg name="ee_cam_x" default="0.035"/>
  <xacro:arg name="ee_cam_y" default="0.0"/>
  <xacro:arg name="ee_cam_z" default="0.0"/>
  <xacro:arg name="ee_cam_roll" default="0.0"/>
  <xacro:arg name="ee_cam_pitch" default="0.0"/>
  <xacro:arg name="ee_cam_yaw" default="0.0"/>

  <xacro:property name="prefix" value="$(arg prefix)"/>
  <xacro:property name="namespace" value="$(arg namespace)"/>
  <xacro:property name="scale" value="$(arg scale)"/>
  <xacro:property name="controllers_file" value="$(arg controllers_file)"/>
  <xacro:property name="visual_mode" value="$(arg visual_mode)"/>
  <xacro:property name="base_height" value="${0.10 * scale}"/>
  <xacro:property name="arm_mount_height" value="$(arg arm_z)"/>
  <xacro:property name="arm_mount_z" value="${base_height + arm_mount_height}"/>
  <xacro:property name="base_visual_enabled" value="${visual_mode == 'full' or visual_mode == 'base_only'}"/>
  <xacro:property name="lidar_topic" value="$(eval '/' + namespace + '/scan' if namespace != '' else '/scan')"/>
  <xacro:property name="cam_front_topic" value="$(eval '/' + namespace + '/camera/front/image_raw' if namespace != '' else '/camera/front/image_raw')"/>
  <xacro:property name="cam_left_topic" value="$(eval '/' + namespace + '/camera/left/image_raw' if namespace != '' else '/camera/left/image_raw')"/>
  <xacro:property name="cam_right_topic" value="$(eval '/' + namespace + '/camera/right/image_raw' if namespace != '' else '/camera/right/image_raw')"/>
  <xacro:property name="cam_rear_topic" value="$(eval '/' + namespace + '/camera/rear/image_raw' if namespace != '' else '/camera/rear/image_raw')"/>
  <xacro:property name="ee_cam_topic" value="$(eval '/' + namespace + '/camera/ee/image_raw' if namespace != '' else '/camera/ee/image_raw')"/>

  <xacro:mm_base
    prefix="${prefix}"
    scale="${scale}"
    visual_mode="$(arg visual_mode)"
    cam_front_x="$(arg cam_front_x)"
    cam_front_y="$(arg cam_front_y)"
    cam_front_z="$(arg cam_front_z)"
    cam_front_roll="$(arg cam_front_roll)"
    cam_front_pitch="$(arg cam_front_pitch)"
    cam_front_yaw="$(arg cam_front_yaw)"
    cam_left_x="$(arg cam_left_x)"
    cam_left_y="$(arg cam_left_y)"
    cam_left_z="$(arg cam_left_z)"
    cam_left_roll="$(arg cam_left_roll)"
    cam_left_pitch="$(arg cam_left_pitch)"
    cam_left_yaw="$(arg cam_left_yaw)"
    cam_right_x="$(arg cam_right_x)"
    cam_right_y="$(arg cam_right_y)"
    cam_right_z="$(arg cam_right_z)"
    cam_right_roll="$(arg cam_right_roll)"
    cam_right_pitch="$(arg cam_right_pitch)"
    cam_right_yaw="$(arg cam_right_yaw)"
    cam_rear_x="$(arg cam_rear_x)"
    cam_rear_y="$(arg cam_rear_y)"
    cam_rear_z="$(arg cam_rear_z)"
    cam_rear_roll="$(arg cam_rear_roll)"
    cam_rear_pitch="$(arg cam_rear_pitch)"
    cam_rear_yaw="$(arg cam_rear_yaw)"
  />
  <xacro:mm_arm
    prefix="${prefix}"
    scale="${scale}"
    arm_mount_height="${arm_mount_height}"
    visual_mode="$(arg visual_mode)"
    ee_cam_mount_x="$(arg ee_cam_mount_x)"
    ee_cam_mount_y="$(arg ee_cam_mount_y)"
    ee_cam_mount_z="$(arg ee_cam_mount_z)"
    ee_cam_mount_roll="$(arg ee_cam_mount_roll)"
    ee_cam_mount_pitch="$(arg ee_cam_mount_pitch)"
    ee_cam_mount_yaw="$(arg ee_cam_mount_yaw)"
    ee_cam_x="$(arg ee_cam_x)"
    ee_cam_y="$(arg ee_cam_y)"
    ee_cam_z="$(arg ee_cam_z)"
    ee_cam_roll="$(arg ee_cam_roll)"
    ee_cam_pitch="$(arg ee_cam_pitch)"
    ee_cam_yaw="$(arg ee_cam_yaw)"
  />

  <joint name="${prefix}base_to_arm_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}arm_root_link"/>
    <origin xyz="$(arg arm_x) $(arg arm_y) ${arm_mount_z}" rpy="$(arg arm_roll) $(arg arm_pitch) $(arg arm_yaw)"/>
  </joint>

  <xacro:if value="$(arg enable_lidar)">
    <link name="${prefix}lidar_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.2"/>
        <inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.0002"/>
      </inertial>
      <xacro:if value="${base_visual_enabled}">
        <visual>
          <geometry>
            <cylinder radius="0.03" length="0.05"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <cylinder radius="0.03" length="0.05"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}lidar_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}lidar_link"/>
      <origin xyz="$(arg lidar_x) $(arg lidar_y) $(arg lidar_z)" rpy="0 0 0"/>
    </joint>

    <gazebo reference="${prefix}lidar_link">
      <sensor name="${prefix}lidar" type="gpu_lidar">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>10</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>720</samples>
              <resolution>1</resolution>
              <min_angle>-3.14159</min_angle>
              <max_angle>3.14159</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.05</min>
            <max>20.0</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <topic>${lidar_topic}</topic>
      </sensor>
    </gazebo>
  </xacro:if>

  <gazebo reference="${prefix}cam_front_link">
    <sensor name="${prefix}cam_front" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>15</update_rate>
      <topic>${cam_front_topic}</topic>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>20.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

  <gazebo reference="${prefix}cam_left_link">
    <sensor name="${prefix}cam_left" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>15</update_rate>
      <topic>${cam_left_topic}</topic>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>20.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

  <gazebo reference="${prefix}cam_right_link">
    <sensor name="${prefix}cam_right" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>15</update_rate>
      <topic>${cam_right_topic}</topic>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>20.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

  <gazebo reference="${prefix}cam_rear_link">
    <sensor name="${prefix}cam_rear" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>15</update_rate>
      <topic>${cam_rear_topic}</topic>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>20.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

  <gazebo reference="${prefix}ee_cam_link">
    <sensor name="${prefix}ee_cam" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>15</update_rate>
      <topic>${ee_cam_topic}</topic>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>20.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

  <xacro:if value="$(arg enable_ros2_control)">
    <xacro:if value="$(eval controllers_file != '')">
      <ros2_control name="mm_mobile_system" type="system">
        <hardware>
          <plugin>gz_ros2_control/GazeboSimSystem</plugin>
        </hardware>

        <joint name="${prefix}front_left_wheel_joint">
          <command_interface name="velocity"/>
          <state_interface name="position"/>
          <state_interface name="velocity"/>
        </joint>
        <joint name="${prefix}front_right_wheel_joint">
          <command_interface name="velocity"/>
          <state_interface name="position"/>
          <state_interface name="velocity"/>
        </joint>
        <joint name="${prefix}rear_left_wheel_joint">
          <command_interface name="velocity"/>
          <state_interface name="position"/>
          <state_interface name="velocity"/>
        </joint>
        <joint name="${prefix}rear_right_wheel_joint">
          <command_interface name="velocity"/>
          <state_interface name="position"/>
          <state_interface name="velocity"/>
        </joint>

        <joint name="${prefix}arm_shoulder_pan_joint">
          <command_interface name="position"/>
          <state_interface name="position"/>
          <state_interface name="velocity"/>
        </joint>
        <joint name="${prefix}arm_shoulder_lift_joint">
          <command_interface name="position"/>
          <state_interface name="position"/>
          <state_interface name="velocity"/>
        </joint>
        <joint name="${prefix}arm_elbow_joint">
          <command_interface name="position"/>
          <state_interface name="position"/>
          <state_interface name="velocity"/>
        </joint>
        <joint name="${prefix}arm_wrist_1_joint">
          <command_interface name="position"/>
          <state_interface name="position"/>
          <state_interface name="velocity"/>
        </joint>
        <joint name="${prefix}arm_wrist_2_joint">
          <command_interface name="position"/>
          <state_interface name="position"/>
          <state_interface name="velocity"/>
        </joint>
        <joint name="${prefix}arm_wrist_3_joint">
          <command_interface name="position"/>
          <state_interface name="position"/>
          <state_interface name="velocity"/>
        </joint>
        <joint name="${prefix}gripper_joint">
          <command_interface name="position"/>
          <state_interface name="position"/>
          <state_interface name="velocity"/>
        </joint>
      </ros2_control>

      <gazebo>
        <plugin filename="libgz_ros2_control-system.so" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
          <ros>
            <namespace>$(arg namespace)</namespace>
          </ros>
          <parameters>${controllers_file}</parameters>
          <controller_manager_name>controller_manager</controller_manager_name>
        </plugin>
      </gazebo>
    </xacro:if>
  </xacro:if>
</robot>
