set(_AMENT_PACKAGE_NAME "mm_bringup")
set(mm_bringup_VERSION "0.0.0")
set(mm_bringup_MAINTAINER "root <root@todo.todo>")
set(mm_bringup_BUILD_DEPENDS )
set(mm_bringup_BUILDTOOL_DEPENDS "ament_cmake")
set(mm_bringup_BUILD_EXPORT_DEPENDS )
set(mm_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(mm_bringup_EXEC_DEPENDS "launch" "launch_ros" "xacro" "robot_state_publisher" "joint_state_publisher_gui" "rviz2" "controller_manager" "ros2_controllers" "ros_gz_sim" "ros_gz_bridge" "teleop_twist_keyboard" "rclpy" "std_msgs")
set(mm_bringup_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(mm_bringup_GROUP_DEPENDS )
set(mm_bringup_MEMBER_OF_GROUPS )
set(mm_bringup_DEPRECATED "")
set(mm_bringup_EXPORT_TAGS)
list(APPEND mm_bringup_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
