<?xml version="1.0"?>
<robot name="mm_base" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:arg name="prefix" default="mm_base_"/>
  <xacro:arg name="scale" default="1.0"/>
  <xacro:arg name="controllers_file" default="$(find-pkg-share mm_bringup)/config/base_controllers.yaml"/>
  <xacro:property name="prefix" value="$(arg prefix)"/>
  <xacro:property name="scale" value="$(arg scale)"/>
  <xacro:property name="controllers_file" value="$(arg controllers_file)"/>

  <!-- Dimensiones ajustables de la base (usar scale para iterar rÃ¡pido). -->
  <xacro:property name="base_length" value="${0.45 * scale}"/>
  <xacro:property name="base_width" value="${0.45 * scale}"/>
  <xacro:property name="base_height" value="${0.12 * scale}"/>

  <xacro:property name="wheel_radius" value="${0.06 * scale}"/>
  <xacro:property name="wheel_width" value="${0.03 * scale}"/>

  <xacro:property name="wheel_x" value="${base_length / 2.0 - wheel_radius}"/>
  <xacro:property name="wheel_y" value="${base_width / 2.0 - wheel_radius}"/>
  <xacro:property name="wheel_z" value="${wheel_radius - base_height / 2.0}"/>

  <!-- Desplazamientos para montar los sensores. -->
  <xacro:property name="lidar_x" value="${base_length / 2.0 - 0.08 * scale}"/>
  <xacro:property name="lidar_z" value="${base_height / 2.0 + 0.18 * scale}"/>
  <xacro:property name="camera_x" value="${base_length / 2.0 + 0.02 * scale}"/>
  <xacro:property name="camera_z" value="${base_height / 2.0 + 0.10 * scale}"/>
  <xacro:property name="nav_camera_x" value="${0.0}"/>
  <xacro:property name="nav_camera_z" value="${base_height / 2.0 + 0.22 * scale}"/>
  <xacro:property name="nav_camera_fov" value="${1.047}"/>
  <xacro:property name="nav_camera_width" value="640"/>
  <xacro:property name="nav_camera_height" value="480"/>

  <xacro:macro name="simple_inertial" params="mass inertia">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${inertia}" ixy="0" ixz="0" iyy="${inertia}" iyz="0" izz="${inertia}"/>
    </inertial>
  </xacro:macro>

  <link name="${prefix}base_footprint"/>

  <joint name="${prefix}base_footprint_joint" type="fixed">
    <parent link="${prefix}base_footprint"/>
    <child link="${prefix}base_link"/>
    <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="12.0"/>
      <inertia ixx="0.18" ixy="0" ixz="0" iyy="0.18" iyz="0" izz="0.22"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="BaseBlue">
        <color rgba="0.1 0.3 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <xacro:macro name="wheel" params="name x y">
    <link name="${prefix}${name}_wheel_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.8"/>
        <inertia ixx="0.002" ixy="0" ixz="0" iyy="0.002" iyz="0" izz="0.002"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${pi / 2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="WheelGray">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi / 2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}${name}_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}${name}_wheel_link"/>
      <origin xyz="${x} ${y} ${wheel_z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1" friction="0.0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel name="front_left" x="${wheel_x}" y="${wheel_y}"/>
  <xacro:wheel name="front_right" x="${wheel_x}" y="${-wheel_y}"/>
  <xacro:wheel name="rear_left" x="${-wheel_x}" y="${wheel_y}"/>
  <xacro:wheel name="rear_right" x="${-wheel_x}" y="${-wheel_y}"/>

  <!-- Sensores -->
  <link name="${prefix}lidar_link">
    <xacro:simple_inertial mass="0.2" inertia="0.0005"/>
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.04"/>
      </geometry>
      <material name="LidarBlack">
        <color rgba="0.05 0.05 0.05 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.03" length="0.04"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}lidar_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}lidar_link"/>
    <origin xyz="${lidar_x} 0 ${lidar_z}" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}camera_link">
    <xacro:simple_inertial mass="0.2" inertia="0.0005"/>
    <visual>
      <geometry>
        <box size="0.05 0.03 0.03"/>
      </geometry>
      <material name="CameraBlack">
        <color rgba="0.05 0.05 0.05 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.03 0.03"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}camera_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}camera_link"/>
    <origin xyz="${camera_x} 0 ${camera_z}" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}imu_link">
    <xacro:simple_inertial mass="0.05" inertia="0.0001"/>
  </link>

  <joint name="${prefix}imu_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}imu_link"/>
    <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}nav_camera_link">
    <xacro:simple_inertial mass="0.2" inertia="0.0005"/>
    <visual>
      <geometry>
        <box size="0.05 0.03 0.03"/>
      </geometry>
      <material name="CameraBlack">
        <color rgba="0.05 0.05 0.05 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.03 0.03"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}nav_camera_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}nav_camera_link"/>
    <origin xyz="${nav_camera_x} 0 ${nav_camera_z}" rpy="0 0 0"/>
  </joint>

  <!-- ros2_control para la base mecanum -->
  <ros2_control name="mm_base_system" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>

    <joint name="${prefix}front_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="${prefix}front_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="${prefix}rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="${prefix}rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin filename="libgz_ros2_control-system.so"
            name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <ros>
        <namespace>mm_base</namespace>
      </ros>
      <parameters>${controllers_file}</parameters>
      <controller_manager_name>${prefix}controller_manager</controller_manager_name>
    </plugin>
  </gazebo>

  <gazebo reference="${prefix}lidar_link">
    <sensor name="lidar" type="gpu_lidar">
      <topic>/mm_base/scan</topic>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>640</samples>
            <resolution>1</resolution>
            <min_angle>-1.396263</min_angle>
            <max_angle>1.396263</max_angle>
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>0.01</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.10</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <always_on>1</always_on>
      <visualize>true</visualize>
    </sensor>
  </gazebo>

  <gazebo reference="${prefix}camera_link">
    <sensor name="camera" type="camera">
      <topic>/mm_base/camera</topic>
      <update_rate>30</update_rate>
      <always_on>1</always_on>
      <visualize>true</visualize>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>50.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

  <gazebo reference="${prefix}imu_link">
    <sensor name="imu" type="imu">
      <topic>/mm_base/imu</topic>
      <update_rate>100</update_rate>
      <always_on>1</always_on>
    </sensor>
  </gazebo>

  <gazebo reference="${prefix}nav_camera_link">
    <sensor name="nav_camera" type="camera">
      <topic>/mm_base/nav_camera</topic>
      <update_rate>15</update_rate>
      <always_on>1</always_on>
      <visualize>true</visualize>
      <camera>
        <horizontal_fov>${nav_camera_fov}</horizontal_fov>
        <image>
          <width>${nav_camera_width}</width>
          <height>${nav_camera_height}</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>60.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>
</robot>
