<?xml version="1.0"?>
<robot name="mm_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:arg name="prefix" default="mm_arm_"/>
  <xacro:arg name="scale" default="1.0"/>
  <xacro:arg name="controllers_file" default="$(find-pkg-share mm_bringup)/config/arm_controllers.yaml"/>
  <xacro:property name="prefix" value="$(arg prefix)"/>
  <xacro:property name="scale" value="$(arg scale)"/>
  <xacro:property name="controllers_file" value="$(arg controllers_file)"/>

  <!-- Placeholder geometry (scale for quick iteration). -->
  <xacro:property name="link1_len" value="${0.22 * scale}"/>
  <xacro:property name="link2_len" value="${0.22 * scale}"/>
  <xacro:property name="link3_len" value="${0.18 * scale}"/>
  <xacro:property name="link4_len" value="${0.14 * scale}"/>
  <xacro:property name="link5_len" value="${0.12 * scale}"/>
  <xacro:property name="link6_len" value="${0.10 * scale}"/>

  <xacro:macro name="simple_inertial" params="mass inertia origin_z">
    <inertial>
      <origin xyz="0 0 ${origin_z}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${inertia}" ixy="0" ixz="0" iyy="${inertia}" iyz="0" izz="${inertia}"/>
    </inertial>
  </xacro:macro>

  <link name="${prefix}root_link"/>

  <link name="${prefix}base_link">
    <xacro:simple_inertial mass="3.0" inertia="0.02" origin_z="0.02"/>
    <visual>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <geometry>
        <box size="0.12 0.12 0.04"/>
      </geometry>
      <material name="ArmGray">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <geometry>
        <box size="0.12 0.12 0.04"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}root_joint" type="fixed">
    <parent link="${prefix}root_link"/>
    <child link="${prefix}base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}link_1">
    <xacro:simple_inertial mass="1.2" inertia="0.01" origin_z="${link1_len / 2.0}"/>
    <visual>
      <origin xyz="0 0 ${link1_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.06 0.06 ${link1_len}"/>
      </geometry>
      <material name="ArmOrange">
        <color rgba="0.9 0.5 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${link1_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.06 0.06 ${link1_len}"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}shoulder_pan_joint" type="revolute">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}link_1"/>
    <origin xyz="0 0 0.04" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi}" upper="${pi}" effort="30" velocity="2"/>
  </joint>

  <link name="${prefix}link_2">
    <xacro:simple_inertial mass="1.1" inertia="0.01" origin_z="${link2_len / 2.0}"/>
    <visual>
      <origin xyz="0 0 ${link2_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 ${link2_len}"/>
      </geometry>
      <material name="ArmOrange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${link2_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 ${link2_len}"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}shoulder_lift_joint" type="revolute">
    <parent link="${prefix}link_1"/>
    <child link="${prefix}link_2"/>
    <origin xyz="0 0 ${link1_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="30" velocity="2"/>
  </joint>

  <link name="${prefix}link_3">
    <xacro:simple_inertial mass="1.0" inertia="0.008" origin_z="${link3_len / 2.0}"/>
    <visual>
      <origin xyz="0 0 ${link3_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.045 0.045 ${link3_len}"/>
      </geometry>
      <material name="ArmOrange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${link3_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.045 0.045 ${link3_len}"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}elbow_joint" type="revolute">
    <parent link="${prefix}link_2"/>
    <child link="${prefix}link_3"/>
    <origin xyz="0 0 ${link2_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="25" velocity="2"/>
  </joint>

  <link name="${prefix}link_4">
    <xacro:simple_inertial mass="0.8" inertia="0.006" origin_z="${link4_len / 2.0}"/>
    <visual>
      <origin xyz="0 0 ${link4_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 ${link4_len}"/>
      </geometry>
      <material name="ArmOrange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${link4_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 ${link4_len}"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}wrist_1_joint" type="revolute">
    <parent link="${prefix}link_3"/>
    <child link="${prefix}link_4"/>
    <origin xyz="0 0 ${link3_len}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="${-pi}" upper="${pi}" effort="20" velocity="2"/>
  </joint>

  <link name="${prefix}link_5">
    <xacro:simple_inertial mass="0.7" inertia="0.004" origin_z="${link5_len / 2.0}"/>
    <visual>
      <origin xyz="0 0 ${link5_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.035 0.035 ${link5_len}"/>
      </geometry>
      <material name="ArmOrange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${link5_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.035 0.035 ${link5_len}"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}wrist_2_joint" type="revolute">
    <parent link="${prefix}link_4"/>
    <child link="${prefix}link_5"/>
    <origin xyz="0 0 ${link4_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi}" upper="${pi}" effort="20" velocity="2"/>
  </joint>

  <link name="${prefix}link_6">
    <xacro:simple_inertial mass="0.6" inertia="0.003" origin_z="${link6_len / 2.0}"/>
    <visual>
      <origin xyz="0 0 ${link6_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 ${link6_len}"/>
      </geometry>
      <material name="ArmOrange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${link6_len / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 ${link6_len}"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}wrist_3_joint" type="revolute">
    <parent link="${prefix}link_5"/>
    <child link="${prefix}link_6"/>
    <origin xyz="0 0 ${link5_len}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="${-pi}" upper="${pi}" effort="15" velocity="3"/>
  </joint>

  <link name="${prefix}tool0">
    <xacro:simple_inertial mass="0.2" inertia="0.0005" origin_z="0.0"/>
    <visual>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
      <material name="ToolRed">
        <color rgba="0.8 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}tool_joint" type="fixed">
    <parent link="${prefix}link_6"/>
    <child link="${prefix}tool0"/>
    <origin xyz="0 0 ${link6_len}" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}gripper_link">
    <xacro:simple_inertial mass="0.3" inertia="0.0008" origin_z="0.0"/>
    <visual>
      <origin xyz="0.04 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.08 0.02 0.02"/>
      </geometry>
      <material name="ToolRed"/>
    </visual>
    <collision>
      <origin xyz="0.04 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.08 0.02 0.02"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}gripper_joint" type="fixed">
    <parent link="${prefix}tool0"/>
    <child link="${prefix}gripper_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Sensors on the end-effector. -->
  <link name="${prefix}ee_camera_link">
    <xacro:simple_inertial mass="0.1" inertia="0.0003" origin_z="0.0"/>
    <visual>
      <geometry>
        <box size="0.04 0.03 0.03"/>
      </geometry>
      <material name="CameraBlack">
        <color rgba="0.05 0.05 0.05 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.04 0.03 0.03"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}ee_camera_joint" type="fixed">
    <parent link="${prefix}tool0"/>
    <child link="${prefix}ee_camera_link"/>
    <origin xyz="0.02 0 0.06" rpy="0 -0.2 0"/>
  </joint>

  <link name="${prefix}ee_imu_link">
    <xacro:simple_inertial mass="0.05" inertia="0.0001" origin_z="0.0"/>
  </link>

  <joint name="${prefix}ee_imu_joint" type="fixed">
    <parent link="${prefix}tool0"/>
    <child link="${prefix}ee_imu_link"/>
    <origin xyz="0 0 0.04" rpy="0 0 0"/>
  </joint>

  <!-- ros2_control for 6DOF arm (encoders -> joint states). -->
  <ros2_control name="mm_arm_system" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>

    <joint name="${prefix}shoulder_pan_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="${prefix}shoulder_lift_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="${prefix}elbow_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="${prefix}wrist_1_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="${prefix}wrist_2_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="${prefix}wrist_3_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin filename="libgz_ros2_control-system.so"
            name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <ros>
        <namespace>mm_arm</namespace>
      </ros>
      <parameters>${controllers_file}</parameters>
      <controller_manager_name>${prefix}controller_manager</controller_manager_name>
    </plugin>
  </gazebo>

  <gazebo reference="${prefix}ee_camera_link">
    <sensor name="ee_camera" type="camera">
      <topic>/mm_arm/camera</topic>
      <update_rate>30</update_rate>
      <always_on>1</always_on>
      <visualize>true</visualize>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>20.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

  <gazebo reference="${prefix}ee_imu_link">
    <sensor name="ee_imu" type="imu">
      <topic>/mm_arm/imu</topic>
      <update_rate>100</update_rate>
      <always_on>1</always_on>
    </sensor>
  </gazebo>
</robot>
