<?xml version="1.0"?>
<robot name="mm_base" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:arg name="prefix" default="mm1_"/>
  <xacro:arg name="namespace" default="mm1"/>
  <xacro:arg name="scale" default="1.0"/>
  <xacro:arg name="controllers_file" default="$(find-pkg-share mm_bringup)/config/base_controllers.yaml"/>
  <xacro:property name="prefix" value="$(arg prefix)"/>
  <xacro:property name="namespace" value="$(arg namespace)"/>
  <xacro:property name="scale" value="$(arg scale)"/>
  <xacro:property name="controllers_file" value="$(arg controllers_file)"/>

  <xacro:property name="base_length" value="${0.50 * scale}"/>
  <xacro:property name="base_width" value="${0.35 * scale}"/>
  <xacro:property name="base_height" value="${0.10 * scale}"/>
  <xacro:property name="wheel_radius" value="${0.07 * scale}"/>
  <xacro:property name="wheel_width" value="${0.04 * scale}"/>

  <xacro:macro name="simple_inertial" params="mass ixz">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${ixz}" ixy="0" ixz="0" iyy="${ixz}" iyz="0" izz="${ixz}"/>
    </inertial>
  </xacro:macro>

  <link name="${prefix}base_footprint"/>

  <link name="${prefix}base_link">
    <xacro:simple_inertial mass="15.0" ixz="0.25"/>
    <visual>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="BaseBlue">
        <color rgba="0.1 0.2 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}base_footprint_joint" type="fixed">
    <parent link="${prefix}base_footprint"/>
    <child link="${prefix}base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}front_left_wheel_link">
    <xacro:simple_inertial mass="1.0" ixz="0.01"/>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}front_right_wheel_link">
    <xacro:simple_inertial mass="1.0" ixz="0.01"/>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}rear_left_wheel_link">
    <xacro:simple_inertial mass="1.0" ixz="0.01"/>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}rear_right_wheel_link">
    <xacro:simple_inertial mass="1.0" ixz="0.01"/>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}front_left_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}front_left_wheel_link"/>
    <origin xyz="${base_length / 2.0} ${base_width / 2.0} ${wheel_radius}" rpy="0 1.5708 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="${prefix}front_right_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}front_right_wheel_link"/>
    <origin xyz="${base_length / 2.0} -${base_width / 2.0} ${wheel_radius}" rpy="0 1.5708 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="${prefix}rear_left_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}rear_left_wheel_link"/>
    <origin xyz="-${base_length / 2.0} ${base_width / 2.0} ${wheel_radius}" rpy="0 1.5708 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="${prefix}rear_right_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}rear_right_wheel_link"/>
    <origin xyz="-${base_length / 2.0} -${base_width / 2.0} ${wheel_radius}" rpy="0 1.5708 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <ros2_control name="mm_base_system" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>

    <joint name="${prefix}front_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="${prefix}front_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="${prefix}rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="${prefix}rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin filename="libgz_ros2_control-system.so" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <ros>
        <namespace>$(arg namespace)</namespace>
      </ros>
      <parameters>${controllers_file}</parameters>
      <controller_manager_name>controller_manager</controller_manager_name>
    </plugin>
  </gazebo>
</robot>
