<?xml version="1.0"?>
<!-- Autor: Camilo Soto Villegas | Contacto: camilo.soto.v@usach.cl | Proyecto: clean_v2 -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="mm_base_simple_inertial" params="mass ixz">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${ixz}" ixy="0" ixz="0" iyy="${ixz}" iyz="0" izz="${ixz}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="mm_base" params="prefix scale visual_mode cam_front_x cam_front_y cam_front_z cam_front_roll cam_front_pitch cam_front_yaw cam_left_x cam_left_y cam_left_z cam_left_roll cam_left_pitch cam_left_yaw cam_right_x cam_right_y cam_right_z cam_right_roll cam_right_pitch cam_right_yaw cam_rear_x cam_rear_y cam_rear_z cam_rear_roll cam_rear_pitch cam_rear_yaw">
    <xacro:property name="base_length" value="${0.50 * scale}"/>
    <xacro:property name="base_width" value="${0.35 * scale}"/>
    <xacro:property name="base_height" value="${0.10 * scale}"/>
    <xacro:property name="base_visual_length" value="${base_length - (0.02 * scale)}"/>
    <xacro:property name="base_visual_width" value="${base_width - (0.02 * scale)}"/>
    <xacro:property name="base_visual_height" value="${base_height - (0.01 * scale)}"/>
    <xacro:property name="wheel_radius" value="${0.07 * scale}"/>
    <xacro:property name="wheel_width" value="${0.04 * scale}"/>

    <link name="${prefix}base_footprint"/>

    <xacro:property name="base_visual_enabled" value="${visual_mode == 'full' or visual_mode == 'base_only'}"/>

    <link name="${prefix}base_link">
      <xacro:mm_base_simple_inertial mass="15.0" ixz="0.25"/>
      <xacro:if value="${base_visual_enabled}">
        <visual>
          <origin xyz="0 0 ${base_visual_height / 2.0}" rpy="0 0 0"/>
          <geometry>
            <box size="${base_visual_length} ${base_visual_width} ${base_visual_height}"/>
          </geometry>
          <material name="BaseBlue">
            <color rgba="0.1 0.2 0.6 1.0"/>
          </material>
        </visual>
      </xacro:if>
      <collision>
        <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <parent link="${prefix}base_footprint"/>
      <child link="${prefix}base_link"/>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}front_left_wheel_link">
      <xacro:mm_base_simple_inertial mass="1.0" ixz="0.01"/>
      <xacro:if value="${base_visual_enabled}">
        <visual>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <link name="${prefix}front_right_wheel_link">
      <xacro:mm_base_simple_inertial mass="1.0" ixz="0.01"/>
      <xacro:if value="${base_visual_enabled}">
        <visual>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <link name="${prefix}rear_left_wheel_link">
      <xacro:mm_base_simple_inertial mass="1.0" ixz="0.01"/>
      <xacro:if value="${base_visual_enabled}">
        <visual>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <link name="${prefix}rear_right_wheel_link">
      <xacro:mm_base_simple_inertial mass="1.0" ixz="0.01"/>
      <xacro:if value="${base_visual_enabled}">
        <visual>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}front_left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_left_wheel_link"/>
      <origin xyz="${base_length / 2.0} ${base_width / 2.0} 0.0" rpy="0 1.5708 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <joint name="${prefix}front_right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_right_wheel_link"/>
      <origin xyz="${base_length / 2.0} -${base_width / 2.0} 0.0" rpy="0 1.5708 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <joint name="${prefix}rear_left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}rear_left_wheel_link"/>
      <origin xyz="-${base_length / 2.0} ${base_width / 2.0} 0.0" rpy="0 1.5708 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <joint name="${prefix}rear_right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}rear_right_wheel_link"/>
      <origin xyz="-${base_length / 2.0} -${base_width / 2.0} 0.0" rpy="0 1.5708 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="${prefix}cam_front_link">
      <xacro:mm_base_simple_inertial mass="0.2" ixz="0.001"/>
      <xacro:if value="${base_visual_enabled}">
        <visual>
          <geometry>
            <box size="0.04 0.03 0.03"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <box size="0.04 0.03 0.03"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}cam_front_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}cam_front_link"/>
      <origin xyz="${cam_front_x} ${cam_front_y} ${cam_front_z}" rpy="${cam_front_roll} ${cam_front_pitch} ${cam_front_yaw}"/>
    </joint>

    <link name="${prefix}cam_left_link">
      <xacro:mm_base_simple_inertial mass="0.2" ixz="0.001"/>
      <xacro:if value="${base_visual_enabled}">
        <visual>
          <geometry>
            <box size="0.04 0.03 0.03"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <box size="0.04 0.03 0.03"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}cam_left_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}cam_left_link"/>
      <origin xyz="${cam_left_x} ${cam_left_y} ${cam_left_z}" rpy="${cam_left_roll} ${cam_left_pitch} ${cam_left_yaw}"/>
    </joint>

    <link name="${prefix}cam_right_link">
      <xacro:mm_base_simple_inertial mass="0.2" ixz="0.001"/>
      <xacro:if value="${base_visual_enabled}">
        <visual>
          <geometry>
            <box size="0.04 0.03 0.03"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <box size="0.04 0.03 0.03"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}cam_right_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}cam_right_link"/>
      <origin xyz="${cam_right_x} ${cam_right_y} ${cam_right_z}" rpy="${cam_right_roll} ${cam_right_pitch} ${cam_right_yaw}"/>
    </joint>

    <link name="${prefix}cam_rear_link">
      <xacro:mm_base_simple_inertial mass="0.2" ixz="0.001"/>
      <xacro:if value="${base_visual_enabled}">
        <visual>
          <geometry>
            <box size="0.04 0.03 0.03"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <box size="0.04 0.03 0.03"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}cam_rear_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}cam_rear_link"/>
      <origin xyz="${cam_rear_x} ${cam_rear_y} ${cam_rear_z}" rpy="${cam_rear_roll} ${cam_rear_pitch} ${cam_rear_yaw}"/>
    </joint>
  </xacro:macro>
</robot>
