<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="mm_base_simple_inertial" params="mass ixz">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${ixz}" ixy="0" ixz="0" iyy="${ixz}" iyz="0" izz="${ixz}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="mm_base" params="prefix scale">
    <xacro:property name="base_length" value="${0.50 * scale}"/>
    <xacro:property name="base_width" value="${0.35 * scale}"/>
    <xacro:property name="base_height" value="${0.10 * scale}"/>
    <xacro:property name="wheel_radius" value="${0.07 * scale}"/>
    <xacro:property name="wheel_width" value="${0.04 * scale}"/>

    <link name="${prefix}base_footprint"/>

    <link name="${prefix}base_link">
      <xacro:mm_base_simple_inertial mass="15.0" ixz="0.25"/>
      <visual>
        <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="BaseBlue">
          <color rgba="0.1 0.2 0.6 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <parent link="${prefix}base_footprint"/>
      <child link="${prefix}base_link"/>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}front_left_wheel_link">
      <xacro:mm_base_simple_inertial mass="1.0" ixz="0.01"/>
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <link name="${prefix}front_right_wheel_link">
      <xacro:mm_base_simple_inertial mass="1.0" ixz="0.01"/>
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <link name="${prefix}rear_left_wheel_link">
      <xacro:mm_base_simple_inertial mass="1.0" ixz="0.01"/>
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <link name="${prefix}rear_right_wheel_link">
      <xacro:mm_base_simple_inertial mass="1.0" ixz="0.01"/>
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}front_left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_left_wheel_link"/>
      <origin xyz="${base_length / 2.0} ${base_width / 2.0} ${wheel_radius}" rpy="0 1.5708 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <joint name="${prefix}front_right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_right_wheel_link"/>
      <origin xyz="${base_length / 2.0} -${base_width / 2.0} ${wheel_radius}" rpy="0 1.5708 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <joint name="${prefix}rear_left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}rear_left_wheel_link"/>
      <origin xyz="-${base_length / 2.0} ${base_width / 2.0} ${wheel_radius}" rpy="0 1.5708 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <joint name="${prefix}rear_right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}rear_right_wheel_link"/>
      <origin xyz="-${base_length / 2.0} -${base_width / 2.0} ${wheel_radius}" rpy="0 1.5708 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>
</robot>
