<?xml version="1.0"?>
<!-- Autor: Camilo Soto Villegas | Contacto: camilo.soto.v@usach.cl | Proyecto: clean_v2 -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Macro para inercia de caja (box) -->
  <xacro:macro name="box_inertial" params="mass x y z *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${(mass/12) * (y*y + z*z)}" ixy="0.0" ixz="0.0"
        iyy="${(mass/12) * (x*x + z*z)}" iyz="0.0"
        izz="${(mass/12) * (x*x + y*y)}"/>
    </inertial>
  </xacro:macro>

  <!-- Macro para inercia de cilindro alineado con eje Z -->
  <xacro:macro name="cylinder_inertial_z" params="mass radius length *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${(mass/12) * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
        iyy="${(mass/12) * (3*radius*radius + length*length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="mm_arm" params="prefix scale visual_mode arm_mount_height ee_cam_mount_x ee_cam_mount_y ee_cam_mount_z ee_cam_mount_roll ee_cam_mount_pitch ee_cam_mount_yaw ee_cam_x ee_cam_y ee_cam_z ee_cam_roll ee_cam_pitch ee_cam_yaw enable_ee_imu ee_imu_x ee_imu_y ee_imu_z ee_imu_roll ee_imu_pitch ee_imu_yaw ee_imu_topic">
    <xacro:property name="link1_len" value="${0.22 * scale}"/>
    <xacro:property name="link2_len" value="${0.22 * scale}"/>
    <xacro:property name="link3_len" value="${0.18 * scale}"/>
    <xacro:property name="link4_len" value="${0.14 * scale}"/>
    <xacro:property name="link5_len" value="${0.12 * scale}"/>
    <xacro:property name="link6_len" value="${0.10 * scale}"/>
    <xacro:property name="arm_mount_height" value="${arm_mount_height}"/>
    <xacro:property name="tool_length" value="${0.04 * scale}"/>
    <xacro:property name="tool_width" value="${0.04 * scale}"/>
    <xacro:property name="tool_height" value="${0.04 * scale}"/>
    <xacro:property name="tool_visual_x" value="${tool_length / 2.0}"/>
    <xacro:property name="gripper_length" value="${0.08 * scale}"/>
    <xacro:property name="gripper_width" value="${0.02 * scale}"/>
    <xacro:property name="gripper_height" value="${0.02 * scale}"/>
    <xacro:property name="gripper_visual_x" value="${gripper_length / 2.0}"/>

    <xacro:property name="arm_visual_enabled" value="${visual_mode == 'full' or visual_mode == 'arm_only'}"/>

    <link name="${prefix}arm_root_link">
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <origin xyz="0 0 0.01" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="0.05" length="0.02"/>
          </geometry>
        </visual>
      </xacro:if>
    </link>

    <link name="${prefix}arm_base_link">
      <xacro:box_inertial mass="4.0" x="0.12" y="0.12" z="0.04">
        <origin xyz="0 0 0.02" rpy="0 0 0"/>
      </xacro:box_inertial>
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <origin xyz="0 0 0.02" rpy="0 0 0"/>
          <geometry>
            <box size="0.12 0.12 0.04"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <origin xyz="0 0 0.02" rpy="0 0 0"/>
        <geometry>
          <box size="0.12 0.12 0.04"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}arm_root_joint" type="fixed">
      <parent link="${prefix}arm_root_link"/>
      <child link="${prefix}arm_base_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}arm_link_1">
      <xacro:box_inertial mass="1.2" x="0.06" y="0.06" z="${link1_len}">
        <origin xyz="0 0 ${link1_len / 2.0}" rpy="0 0 0"/>
      </xacro:box_inertial>
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <origin xyz="0 0 ${link1_len / 2.0}" rpy="0 0 0"/>
          <geometry>
            <box size="0.06 0.06 ${link1_len}"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <origin xyz="0 0 ${link1_len / 2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="0.06 0.06 ${link1_len}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}arm_shoulder_pan_joint" type="revolute">
      <parent link="${prefix}arm_base_link"/>
      <child link="${prefix}arm_link_1"/>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-3.14" upper="3.14" effort="50" velocity="1.0"/>
    </joint>

    <link name="${prefix}arm_link_2">
      <xacro:box_inertial mass="1.0" x="0.05" y="0.05" z="${link2_len}">
        <origin xyz="0 0 ${link2_len / 2.0}" rpy="0 0 0"/>
      </xacro:box_inertial>
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <origin xyz="0 0 ${link2_len / 2.0}" rpy="0 0 0"/>
          <geometry>
            <box size="0.05 0.05 ${link2_len}"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <origin xyz="0 0 ${link2_len / 2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 ${link2_len}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}arm_shoulder_lift_joint" type="revolute">
      <parent link="${prefix}arm_link_1"/>
      <child link="${prefix}arm_link_2"/>
      <origin xyz="0 0 ${link1_len}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="1.57" effort="50" velocity="1.0"/>
    </joint>

    <link name="${prefix}arm_link_3">
      <xacro:box_inertial mass="0.8" x="0.05" y="0.05" z="${link3_len}">
        <origin xyz="0 0 ${link3_len / 2.0}" rpy="0 0 0"/>
      </xacro:box_inertial>
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <origin xyz="0 0 ${link3_len / 2.0}" rpy="0 0 0"/>
          <geometry>
            <box size="0.05 0.05 ${link3_len}"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <origin xyz="0 0 ${link3_len / 2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 ${link3_len}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}arm_elbow_joint" type="revolute">
      <parent link="${prefix}arm_link_2"/>
      <child link="${prefix}arm_link_3"/>
      <origin xyz="0 0 ${link2_len}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-2.0" upper="2.0" effort="40" velocity="1.2"/>
    </joint>

    <link name="${prefix}arm_link_4">
      <xacro:box_inertial mass="0.6" x="0.045" y="0.045" z="${link4_len}">
        <origin xyz="0 0 ${link4_len / 2.0}" rpy="0 0 0"/>
      </xacro:box_inertial>
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <origin xyz="0 0 ${link4_len / 2.0}" rpy="0 0 0"/>
          <geometry>
            <box size="0.045 0.045 ${link4_len}"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <origin xyz="0 0 ${link4_len / 2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="0.045 0.045 ${link4_len}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}arm_wrist_1_joint" type="revolute">
      <parent link="${prefix}arm_link_3"/>
      <child link="${prefix}arm_link_4"/>
      <origin xyz="0 0 ${link3_len}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-2.5" upper="2.5" effort="20" velocity="1.5"/>
    </joint>

    <link name="${prefix}arm_link_5">
      <xacro:box_inertial mass="0.4" x="0.04" y="0.04" z="${link5_len}">
        <origin xyz="0 0 ${link5_len / 2.0}" rpy="0 0 0"/>
      </xacro:box_inertial>
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <origin xyz="0 0 ${link5_len / 2.0}" rpy="0 0 0"/>
          <geometry>
            <box size="0.04 0.04 ${link5_len}"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <origin xyz="0 0 ${link5_len / 2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="0.04 0.04 ${link5_len}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}arm_wrist_2_joint" type="revolute">
      <parent link="${prefix}arm_link_4"/>
      <child link="${prefix}arm_link_5"/>
      <origin xyz="0 0 ${link4_len}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="-3.14" upper="3.14" effort="15" velocity="1.8"/>
    </joint>

    <link name="${prefix}arm_link_6">
      <xacro:box_inertial mass="0.3" x="0.035" y="0.035" z="${link6_len}">
        <origin xyz="0 0 ${link6_len / 2.0}" rpy="0 0 0"/>
      </xacro:box_inertial>
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <origin xyz="0 0 ${link6_len / 2.0}" rpy="0 0 0"/>
          <geometry>
            <box size="0.035 0.035 ${link6_len}"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <origin xyz="0 0 ${link6_len / 2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="0.035 0.035 ${link6_len}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}arm_wrist_3_joint" type="revolute">
      <parent link="${prefix}arm_link_5"/>
      <child link="${prefix}arm_link_6"/>
      <origin xyz="0 0 ${link5_len}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-3.14" upper="3.14" effort="10" velocity="2.0"/>
    </joint>

    <link name="${prefix}tool0">
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <origin xyz="${tool_visual_x} 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${tool_length} ${tool_width} ${tool_height}"/>
          </geometry>
        </visual>
      </xacro:if>
    </link>
    <joint name="${prefix}tool_joint" type="fixed">
      <parent link="${prefix}arm_link_6"/>
      <child link="${prefix}tool0"/>
      <origin xyz="0 0 ${link6_len}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}ee_cam_mount_link">
      <xacro:cylinder_inertial_z mass="0.2" radius="0.015" length="0.03">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:cylinder_inertial_z>
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <geometry>
            <cylinder radius="0.015" length="0.03"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <cylinder radius="0.015" length="0.03"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}ee_cam_mount_joint" type="fixed">
      <parent link="${prefix}tool0"/>
      <child link="${prefix}ee_cam_mount_link"/>
      <origin xyz="${ee_cam_mount_x} ${ee_cam_mount_y} ${ee_cam_mount_z}" rpy="${ee_cam_mount_roll} ${ee_cam_mount_pitch} ${ee_cam_mount_yaw}"/>
    </joint>

    <link name="${prefix}ee_cam_link">
      <xacro:box_inertial mass="0.2" x="0.04" y="0.03" z="0.03">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:box_inertial>
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <geometry>
            <box size="0.04 0.03 0.03"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <box size="0.04 0.03 0.03"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}ee_cam_joint" type="fixed">
      <parent link="${prefix}ee_cam_mount_link"/>
      <child link="${prefix}ee_cam_link"/>
      <origin xyz="${ee_cam_x} ${ee_cam_y} ${ee_cam_z}" rpy="${ee_cam_roll} ${ee_cam_pitch} ${ee_cam_yaw}"/>
    </joint>

    <xacro:if value="${enable_ee_imu}">
      <link name="${prefix}ee_imu_link">
        <xacro:box_inertial mass="0.1" x="0.03" y="0.03" z="0.02">
          <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:box_inertial>
        <xacro:if value="${arm_visual_enabled}">
          <visual>
            <geometry>
              <box size="0.03 0.03 0.02"/>
            </geometry>
          </visual>
        </xacro:if>
        <collision>
          <geometry>
            <box size="0.03 0.03 0.02"/>
          </geometry>
        </collision>
      </link>

      <joint name="${prefix}ee_imu_joint" type="fixed">
        <parent link="${prefix}tool0"/>
        <child link="${prefix}ee_imu_link"/>
        <origin xyz="${ee_imu_x} ${ee_imu_y} ${ee_imu_z}" rpy="${ee_imu_roll} ${ee_imu_pitch} ${ee_imu_yaw}"/>
      </joint>

      <gazebo reference="${prefix}ee_imu_link">
        <sensor name="${prefix}ee_imu" type="imu">
          <pose>0 0 0 0 0 0</pose>
          <always_on>1</always_on>
          <update_rate>100</update_rate>
          <topic>${ee_imu_topic}</topic>
          <imu>
            <linear_acceleration>
              <x>
                <noise type="gaussian">
                  <mean>0.0</mean>
                  <stddev>0.01</stddev>
                </noise>
              </x>
              <y>
                <noise type="gaussian">
                  <mean>0.0</mean>
                  <stddev>0.01</stddev>
                </noise>
              </y>
              <z>
                <noise type="gaussian">
                  <mean>0.0</mean>
                  <stddev>0.01</stddev>
                </noise>
              </z>
            </linear_acceleration>
            <angular_velocity>
              <x>
                <noise type="gaussian">
                  <mean>0.0</mean>
                  <stddev>0.001</stddev>
                </noise>
              </x>
              <y>
                <noise type="gaussian">
                  <mean>0.0</mean>
                  <stddev>0.001</stddev>
                </noise>
              </y>
              <z>
                <noise type="gaussian">
                  <mean>0.0</mean>
                  <stddev>0.001</stddev>
                </noise>
              </z>
            </angular_velocity>
          </imu>
        </sensor>
      </gazebo>
    </xacro:if>

    <link name="${prefix}gripper_link">
      <xacro:box_inertial mass="0.2" x="${gripper_length}" y="${gripper_width}" z="${gripper_height}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:box_inertial>
      <xacro:if value="${arm_visual_enabled}">
        <visual>
          <origin xyz="${gripper_visual_x} 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${gripper_length} ${gripper_width} ${gripper_height}"/>
          </geometry>
        </visual>
      </xacro:if>
      <collision>
        <origin xyz="${gripper_visual_x} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${gripper_length} ${gripper_width} ${gripper_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}gripper_joint" type="prismatic">
      <parent link="${prefix}tool0"/>
      <child link="${prefix}gripper_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="0.0" upper="0.04" effort="20" velocity="0.2"/>
    </joint>
  </xacro:macro>
</robot>
