set(_AMENT_PACKAGE_NAME "mm_base_description")
set(mm_base_description_VERSION "0.1.0")
set(mm_base_description_MAINTAINER "Camilo Soto Villegas <camilo.soto.v@usach.cl>")
set(mm_base_description_BUILD_DEPENDS "xacro")
set(mm_base_description_BUILDTOOL_DEPENDS "ament_cmake")
set(mm_base_description_BUILD_EXPORT_DEPENDS "xacro")
set(mm_base_description_BUILDTOOL_EXPORT_DEPENDS )
set(mm_base_description_EXEC_DEPENDS "xacro")
set(mm_base_description_TEST_DEPENDS )
set(mm_base_description_GROUP_DEPENDS )
set(mm_base_description_MEMBER_OF_GROUPS )
set(mm_base_description_DEPRECATED "")
set(mm_base_description_EXPORT_TAGS)
list(APPEND mm_base_description_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
